server:
  port: 8090
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ROOT_USER}
    password: ${ROOT_PASSWORD}
  jpa:
    show-sql: true
